---

- name: Include vars
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Set hostname
  ansible.builtin.include_tasks: hostname.yml
  when:
    - system_hostname is defined
    - system_hostname|length > 0

- name: Install packages
  ansible.builtin.include_tasks: packages.yml

- name: QEMU guest agent
  ansible.builtin.include_tasks: qemu-agent.yml
  when:
    - system_qemu_agent_install
    - ansible_system_vendor == "QEMU"

- name: Configure system locale and timezone
  ansible.builtin.include_tasks: locale.yml

- name: Copy /etc/skel
  ansible.builtin.include_tasks: skel.yml

- name: Add users and groups
  ansible.builtin.include_tasks: users.yml

- name: System hardening
  ansible.builtin.include_tasks: hardening.yml
